---

- name: Cisco show version example
  hosts: all
  gather_facts: false

  tasks:
    - name: run show version on the routers
      ios_command:
        commands: 
          - show hostname
      register: output

    - name: print output
      debug:
        var: output.stdout_lines
