---
- name: Cisco show version example
  hosts: all
  gather_facts: false
  collections:
  - cisco.ios
  vars: # for execution environment
  
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable

  tasks:

    - name: Show 'ansible_*' values
      debug:
        msg: 
          - "{{ ansible_network_os }}"
          - "{{ ansible_connection }}"
    - meta: end_play

    - name: Gather only the config and default facts
      cisco.ios.ios_facts:
        gather_subset:
        - config

    - name: Show facts
      debug:
        msg: "{{ ansible_facts.net_version }}"
