- name: Initial Playbook
  hosts: csr1
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Configure L3 Interface
      ios_config:
        parents:
          - interface g2.101
        lines:
          - encapsulation dot1Q 101
          - ip address 10.100.102.253 255.255.255.0
          - description rogi da nogi
      #  after:
      #    - end
       #   - copy run start
       # backup: yes
      register: show_result

    - name: Debug registered var
      debug: var=show_result.stdout_lines
